# Generated by Django 4.2.2 on 2023-08-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_order_code_alter_orderedproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.variant', verbose_name='Вариант товара'),
            preserve_default=False,
        ),
    ]
