# Generated by Django 4.2.2 on 2023-08-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.CharField()),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app.order', verbose_name='Этапы')),
            ],
        ),
    ]
