# Generated by Django 4.2.2 on 2023-08-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип этапа заказа',
                'verbose_name_plural': 'Типы этапа заказа',
            },
        ),
        migrations.AlterModelOptions(
            name='orderstage',
            options={'verbose_name': 'Этап заказа', 'verbose_name_plural': 'Этапы заказа'},
        ),
        migrations.RemoveField(
            model_name='orderstage',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнен ли'),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='stage_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.orderstagetype', verbose_name='Тип этапа'),
            preserve_default=False,
        ),
    ]
