# Generated by Django 4.2.2 on 2023-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_review_product_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли заказ'),
        ),
    ]
