# Generated by Django 4.2.2 on 2023-08-15 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approx_delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Примерная дата доставки'),
        ),
    ]
