# Generated by Django 4.2.2 on 2023-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_approx_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approx_delivery_date',
            field=models.DateTimeField(verbose_name='Примерная дата доставки'),
        ),
    ]
