# Generated by Django 4.2.2 on 2023-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_approx_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approx_delivery_date',
            field=models.DateField(blank=True, verbose_name='Примерная дата доставки'),
        ),
    ]
