# Generated by Django 4.2.2 on 2023-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_order_approx_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstagetype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер этапа'),
        ),
    ]
