# Generated by Django 4.2.2 on 2023-08-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_appeal_alter_order_options_alter_orderstage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ProductTag',
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Тег продукта', 'verbose_name_plural': 'Теги продукта'},
        ),
    ]
