# Generated by Django 4.2.2 on 2023-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_blogtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Изображение')),
                ('heading', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name=' Описание')),
                ('text', models.TextField()),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('tags', models.ManyToManyField(blank=True, to='app.blogtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост в блоге',
                'verbose_name_plural': 'Посты в блоге',
            },
        ),
    ]
