# Generated by Django 4.2.2 on 2023-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='rgb(255, 255, 255)', max_length=18, verbose_name='Цвет аватара (без картинки)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
