# Generated by Django 4.2.2 on 2023-10-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_user_color_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(default='rgb(7, 83, 161)', max_length=18, verbose_name='Цвет аватара (без картинки)'),
        ),
    ]
