# Generated by Django 4.2.2 on 2023-11-07 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_cartitem_amount_alter_orderedproduct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.AddField(
            model_name='variant',
            name='actual_price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена без скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='variant',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
