# Generated by Django 4.2.2 on 2023-11-10 06:03

import app.models.variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_product_subcategory_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(upload_to=app.models.variant.get_upload_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
