# Generated by Django 4.2.2 on 2023-11-10 06:26

import app.models.variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_product_image_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to=app.models.variant.get_upload_path, verbose_name='Изображение'),
        ),
    ]
