# Generated by Django 4.2.2 on 2023-11-10 06:32

import app.models.variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(upload_to=app.models.variant.get_upload_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
