# Generated by Django 4.2.2 on 2023-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
