# Generated by Django 4.2.2 on 2023-11-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_product_is_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.AddField(
            model_name='variant',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='Есть ли в наличии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.category', verbose_name='Родительская категория'),
        ),
    ]
