# Generated by Django 4.2.2 on 2023-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_product_is_in_stock_variant_is_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(blank=True, to='app.variant', verbose_name='Сохраненные товары'),
        ),
    ]
