# Generated by Django 4.2.2 on 2023-11-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_user_saved_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='saved_products',
            new_name='saved_product_variants',
        ),
    ]
