# Generated by Django 4.2.2 on 2023-11-14 12:45

import app.models.ordered_product
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_saved_products_user_saved_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='actual_price',
            field=models.PositiveIntegerField(verbose_name='Цена без скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='image',
            field=models.ImageField(upload_to=app.models.ordered_product.get_upload_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='origin_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.variant', verbose_name='Вариант товара'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variant_name',
            field=models.CharField(default='1L', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
