# Generated by Django 4.2.2 on 2023-11-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_orderedproduct_variant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstagetype',
            options={'ordering': ('ordering',), 'verbose_name': 'Тип этапа заказа', 'verbose_name_plural': 'Типы этапа заказа'},
        ),
        migrations.AddField(
            model_name='orderstagetype',
            name='is_payment_stage',
            field=models.BooleanField(default=False, verbose_name='Является ли этапом оплаты'),
        ),
        migrations.AlterField(
            model_name='orderstagetype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddConstraint(
            model_name='orderstagetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_payment_stage', True)), fields=('is_payment_stage',), name='unique_is_payment_stage'),
        ),
    ]
