# Generated by Django 4.2.2 on 2023-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_orderstagetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
