# Generated by Django 4.2.2 on 2023-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstagetype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
