# Generated by Django 4.2.2 on 2023-11-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_orderstagetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменен ли'),
        ),
        migrations.AlterField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.variant', verbose_name='Вариант'),
        ),
    ]
