# Generated by Django 4.2.2 on 2023-11-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_order_is_cancelled_alter_review_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('ordering',), 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товара'},
        ),
        migrations.AddField(
            model_name='variant',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='origin_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.variant', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='variant_name',
            field=models.CharField(max_length=100, verbose_name='Вариант'),
        ),
    ]
