# Generated by Django 4.2.2 on 2024-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_category_image_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ph_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
