# Generated by Django 4.2.2 on 2024-01-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_product_ph_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страны производители',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='ph_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Уровень pH'),
        ),
        migrations.AddField(
            model_name='brand',
            name='manufacturer_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manufacturercountry', verbose_name='Страна производитель'),
        ),
    ]
