# Generated by Django 4.2.2 on 2024-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_manufacturercountry_alter_product_ph_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Тег товара', 'verbose_name_plural': 'Теги товара'},
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
