# Generated by Django 4.2.2 on 2024-02-11 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_brand_image_alter_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер должен быть введен в формате: '+999999999'. Номер должен содержать не меньше 9 и не больше 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
