# Generated by Django 4.2.2 on 2024-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес в граммах'),
        ),
    ]
