# Generated by Django 4.2.2 on 2024-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_variant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='height',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='length',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='width',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Вес (гр)'),
        ),
    ]
