# Generated by Django 4.2.2 on 2024-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_variant_height_variant_length_variant_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_sum',
            field=models.PositiveIntegerField(verbose_name='Стоимость доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.CharField(max_length=256, verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
