# Generated by Django 4.2.2 on 2024-05-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_order_address_order_delivery_sum_order_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='email',
        ),
    ]
