# Generated by Django 4.2.2 on 2024-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_order_promocode_alter_promocode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз ли'),
        ),
    ]
