# Generated by Django 4.2.2 on 2024-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_order_is_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тариф'),
        ),
    ]
